#!/usr/bin/env python3

# Problem setting
"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	    1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""


def isTriangle(number):

    """Returns True is a number is a triangle number. Returns False otherwise."""

    if number == 1:
        return True
    else:
        n = ((8 * number + 1) ** .5 - 1)
        if n % 2 == 0:
            return True
        else:
            return False


def isPentagonal(number):

    """Returns True is a number is a pentagonal number. Returns False otherwise."""

    if number == 1:
        return True
    else:
        n = ((24 * number + 1) ** .5 + 1)
        if n % 6 == 0:
            return True
        else:
            return False


def isHexagonal(number):

    """Returns True is a number is a hexagonal number. Returns False otherwise."""

    if number == 1:
        return True
    else:
        n = ((8 * number + 1) ** .5 + 1)
        if n % 4 == 0:
            return True
        else:
            return False


def isAll(lowerbound):

    """
    Returns the number which is triangular, pentagonal and hexagonal.
    Starts searching from the specified lower bound + 1.
    """

    searching = True
    num = lowerbound + 1

    while searching:
        if isTriangle(num) and isHexagonal(num) and isPentagonal(num):
            searching = False
        else:
            num += 1

    return num


def main():

    """Main function to get going. Asks the user to input the lower limit (starting point is input + 1)."""

    inputted = int(input("Please specify the lower limit: "))
    result = isAll(inputted)

    print('---')
    print("The smallest number larger than", inputted,
          ", that is pentagonal, triangular and hexagonal at the same time is:", result)
    print('---')
    print("Checks ( all with", result, "as input ):"
          "\nTriangular:", isTriangle(result),
          "\nPentagonal:", isPentagonal(result),
          "\nHexagonal:", isHexagonal(result))


main()
