#!/usr/bin/env python3

# Problem setting:
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""

def fibonacci(limit):
    """Find all fibonacci numbers below a certain limit, and sum those that are evenly divisible by two."""

    startList = [1,2]
    criticalValue = 0
    sumList = [2]
    while criticalValue < limit:
        fibonacciValue = startList[-2] + startList[-1]
        if fibonacciValue % 2 ==0:
            sumList.append(fibonacciValue)
        startList.append(fibonacciValue)
        criticalValue = fibonacciValue

    return sum(sumList)

solution = fibonacci(4000000)
print("The sum of the even fibonacci numbers up to 4.000.000 is: %d." %(solution))